spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://ep-solitary-water-a1k4fpoz-pooler.ap-southeast-1.aws.neon.tech/GarboDB1_dev?sslmode=require&channelBinding=require
    driver-class-name: org.postgresql.Driver
    username: neondb_owner
    password: npg_HeskrVL7l0Pj
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  level:
    root: DEBUG