spring:
  datasource:
    url: ${PROD_SPRING_DATASOURCE_URL}
    driver-class-name: ${PROD_SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${PROD_SPRING_DATASOURCE_USERNAME}
    password: ${PROD_SPRING_DATASOURCE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update # Strict validation in production
    show-sql: false

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    out-of-order: true
    ignore-migration-patterns: "*:missing"
    validate-on-migrate: false
