spring:
  datasource:
    url: ${PROD_SPRING_DATASOURCE_URL}
    driver-class-name: ${PROD_SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${PROD_SPRING_DATASOURCE_USERNAME}
    password: ${PROD_SPRING_DATASOURCE_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: update # Strict validation in production
    show-sql: false

  flyway:
    enabled: false # Flyway should manage production schema
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
