spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:false}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}

server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
